### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by bunnycxx** [jinli-stat/DeepSurvK-R#1]
Why does this error persist during runtime? TensorFlow 2 has already been installed in anaconda. Is there a problem with the connection between R and TensorFlow? Or is there an issue with the versions of R and Python?
<img width="523" alt="微信图片_20240422150016" src="https://github.com/jinli-stat/DeepSurv-R-Keras/assets/167744770/7b3c3e66-d641-4e23-8e7a-c974a5380a86">

**Comment by jinli-stat** [comment]
Thank you.

There are sometimes problems running tensorflow in R. I'm running on CUDA V11.2 + Tensorflow 2.6.0. You can copy my running environment as follows.

Create a virtual environment in conda called `r-tensorflow`:

`conda create --name r-tensorflow --file spec-list.txt`

The file [spec-list.txt](https://github.com/jinli-stat/DeepSurv-R-Keras/files/15058877/spec-list.txt) is attached. 

After install `tensorflow` and `keras` packages in R, run the following code:
```{R}
library(tensorflow)
tf$constant("Hellow Tensorflow")
```
The code returns: `tf.Tensor(b'Hellow Tensorflow', shape=(), dtype=string)`. There may be some warnings, but they are usually unimportant. 

**Note**:  install `tensorflow` in the **`r-tensorflow` environment**, version 2.6.0 is recommended if you want to use GPUs on Windows, otherwise additional settings may be required. If you don't use GPUs, it's also recommended to install tensorflow in the `r-tensorflow` virtual environment first, and then go back to R.
